ministryofjustice/cla_frontend

- cla_frontend/assets-src/javascripts/app/partials/includes/eligibility.expenses.html
- cla_frontend/assets-src/javascripts/app/partials/includes/eligibility.income.html
- tests/angular-js/e2e/meansTest.js
Logically it makes more sense to complete at the same time as being asked your income
> Move NI field to income

- cla_frontend/assets-src/javascripts/app/js/directives/safeToContact.js
- cla_frontend/assets-src/javascripts/app/partials/directives/safe_to_contact.html
- cla_frontend/assets-src/javascripts/app/partials/includes/personal_details.html
- cla_frontend/assets-src/javascripts/app/partials/includes/third_party.html
Not safe to leave a message was same not safe to call icon
> Switch duplicate safe to call/message icon

- cla_frontend/assets-src/javascripts/app/partials/csv_download_list.html
- cla_frontend/assets-src/javascripts/app/partials/csv_upload_list.html
> Show modified instead of created at 'uploaded at' in the csvupload/download

- cla_frontend/assets-src/javascripts/app/partials/provider/case_detail.html
- tests/angular-js/e2e/providerCase.js
> Remove close case confirmation in Provider UI

- cla_frontend/assets-src/javascripts/app/partials/case_list.html
> Provider: Use context-aware copy when no results are present

- cla_frontend/assets-src/javascripts/app/partials/directives/notes_form.html
> Increase notes textarea height

- cla_frontend/assets-src/javascripts/app/partials/notes.history.modal.html
Fixes [86918826](https://www.pivotaltracker.com/story/show/86918826) in Pivotal
> don't show pagination on notes history if there is no history

- cla_frontend/assets-src/javascripts/app/partials/case_detail.alternative_help.html
*  Add survey reminder text to Alternative Help page, as discussed with @teneightfive and @acjnash , text abridged from email from Alice Muskett (LAA)
[Pivotal story 87295520](https://www.pivotaltracker.com/story/show/87295520)
> Add script block for survey reminder

- cla_frontend/assets-src/javascripts/app/js/controllers/alternative_help.js
- cla_frontend/assets-src/javascripts/app/partials/alternative_help_survey.modal.html
- cla_frontend/assets-src/javascripts/app/partials/case_detail.alternative_help.html
- tests/angular-js/e2e/alternativeHelp.js
- tests/angular-js/protractor.conf.js
[PT](https://www.pivotaltracker.com/story/show/87295520)
> Show survey reminder call script in modal overlay

- cla_frontend/assets-src/javascripts/app/js/controllers/personal_details.js
- cla_frontend/assets-src/javascripts/app/js/directives/safeToContact.js
Basically there was no default state for the icon
> more thorough fix for icon bug

- cla_frontend/assets-src/javascripts/app/partials/call_centre/case_list.html
- cla_frontend/assets-src/stylesheets/design-patterns/_label.scss
- cla_frontend/assets-src/stylesheets/design-patterns/_list-table.scss
- tests/angular-js/e2e/caseList.js
Depends on [cla_backend#360](https://github.com/ministryofjustice/cla_backend/pull/360)
> CHS: Call Centre case filtering

- cla_frontend/assets-src/javascripts/app/js/controllers/csv_upload.js
- cla_frontend/assets-src/javascripts/app/js/services/models.js
- cla_frontend/assets-src/javascripts/app/js/states/call_centre/csv_download.js
- cla_frontend/assets-src/javascripts/app/js/states/provider/csv_upload.js
- cla_frontend/assets-src/javascripts/app/partials/csv_download_list.html
- cla_frontend/assets-src/javascripts/app/partials/csv_upload_list.html
depends on [cla_backend/376](https://github.com/ministryofjustice/cla_backend/pull/376)
> CSV download pagination and filtering

- cla_frontend/assets-src/javascripts/app/js/directives/callbackModal.js
- cla_frontend/assets-src/javascripts/app/js/states/call_centre/case_detail.suspend.js
- cla_frontend/assets-src/javascripts/app/partials/directives/callbackModal.html
- cla_frontend/assets-src/stylesheets/design-patterns/_callback-modal.scss
[PT#97809110](https://www.pivotaltracker.com/story/show/97809110)
Depends on [cla_backend#379](https://github.com/ministryofjustice/cla_backend/pull/379)
> Additional outcome codes

- cla_frontend/assets-src/javascripts/app/js/controllers/eligibility_check.js
- cla_frontend/assets-src/javascripts/app/partials/case_detail.edit.eligibility.html
- cla_frontend/assets-src/stylesheets/views/_case.scss
[PT#101751938](https://www.pivotaltracker.com/story/show/101751938)
> Add button to skip Means test

- cla_frontend/assets-src/javascripts/app/js/controllers/call_centre/diversity.js
> Change copy for disability question in diversity call centre script.

- cla_frontend/assets-src/javascripts/app/js/controllers/call_centre/complaints.js
Transferred to specialist option added to complaints.
> Add "transferred to specialist" option for complaints

- cla_frontend/assets-src/javascripts/app/js/controllers/call_centre/diversity.js
- changes as per advice from Rachel
> consistent copy for religion, ethnicity and disability

- cla_frontend/apps/status/smoketests/__init__.py
> LGA-449 Flake8 fixes

- cla_frontend/templates/cla_provider/legal_help_form.jade
> LGA-488 - GDPR updates to CLA Legal Help form

- cla_frontend/assets-src/javascripts/app/js/controllers/personal_details.js
- cla_frontend/assets-src/javascripts/app/js/services/models.js
- cla_frontend/assets-src/javascripts/app/js/states/case_detail.js
- cla_frontend/assets-src/javascripts/app/partials/includes/personal_details.html
- package-lock.json
Added contact_for_research_methods from backend
Allow call centre operators to apply more than one option for research preferences
Related cla_backend PR https://github.com/ministryofjustice/cla_backend/pull/576
Related end-to-end PR https://github.com/ministryofjustice/laa-cla-e2e-tests/pull/48
> LGA-644 - Allow call centre operators to apply more than one option for research preferences

- cla_frontend/assets-src/javascripts/app/partials/case_list.html
Add case organisation to cases dashboard
Do not merge before https://github.com/ministryofjustice/cla_backend/pull/586
> LGA-771 - Add case organisation to cases dashboard

- .circleci/config.yml
- Dockerfile
- cla_frontend/assets-src/javascripts/app/js/directives/callbackModal.js
- cla_frontend/assets-src/javascripts/app/js/directives/callbackStatus.js
- cla_frontend/assets-src/javascripts/app/js/services/models.js
- cla_frontend/assets-src/javascripts/app/partials/case_list.html
- cla_frontend/assets-src/javascripts/app/partials/directives/callbackMatrix.html
- cla_frontend/assets-src/javascripts/app/partials/directives/callbackModal.html
- cla_frontend/assets-src/stylesheets/design-patterns/_callback-modal.scss
Changes interfaces and display values of callback times to be aware that they might represent single times (with an implicit half hour window either side) or an explicit half-hour window.
Accompanies changes to cla_backend and cla_public
Should be reviewed but not merged until we're ready to go live with the change
> DO NOT MERGE LGA-730: Callback window changes

- .circleci/config.yml
- .circleci/define_build_environment_variables
- .circleci/tag_and_push_docker_image
Push images to Live-1 ECR repo
Reverts ministryofjustice/cla_frontend#670
requires https://github.com/ministryofjustice/cloud-platform-environments/pull/1931 (merged)
> LGA-704 - Push images to ECR repository on Live-1

- cla_frontend/assets-src/javascripts/app/js/controllers/personal_details.js
- cla_frontend/assets-src/javascripts/app/partials/includes/personal_details.html
Remove the editing of exempt_user and exempt_user_reason fields
> LGA-1110 - Remove the editing of exempt_user and exempt_user_reason fields

- cla_frontend/assets-src/javascripts/app/js/directives/callbackModal.js
- requirements/lint.txt
Allows callbacks to be scheduled in the current and next callback windows, in addition to all future windows as normal.
Requires corresponding backend change
> LGA-1383 - Remove call back scheduling delay

- cla_frontend/settings/base.py
- requirements/lint.txt
Enable maintenance mode during the migration of cla_backend to cloud platforms
> LGA-LGA-1390 - Enable maintenance mode

- cla_frontend/settings/base.py
Reverts ministryofjustice/cla_frontend#689
> Revert "LGA-LGA-1390 - Enable maintenance mode"

- cla_frontend/assets-src/javascripts/app/partials/includes/eligibility.income.html
Changes the tax calculator that we link to in order to help the operator
accurately record the client's financial situation.
The existing one is apparently several years out of date. The
replacement is both current and official
> LGA-782 - Update link to tax calculator

- README.md
Added alternative commands for Windows users
> Update README.md with alternative Windows commands

- cla_socketserver/README.md
Documenting what the socket server does and how it is used
> LGA 1610 - Documenting what the socket server does and how it is used

- cla_frontend/apps/core/context_processors.py
- cla_frontend/assets-src/javascripts/vendor/raven.config.js
- cla_frontend/templates/base.html
Pass environment label to angular sentry integration
> LGA-1635 - Pass environment label to angular sentry integration

- cla_frontend/assets-src/javascripts/app/js/controllers/eligibility_check.js
- cla_frontend/assets-src/javascripts/app/partials/includes/eligibility.details.html
Change script message depending on if the user journey was a:
- judicial review education case
- any other education case
- anything else
> LGA-1692 Change diagnosis script notes depending on sub category

- Dockerfile
- cla_frontend/apps/core/s3.py
- cla_frontend/apps/status/smoketests/basic.py
- cla_frontend/settings/base.py
- requirements/base.txt
Serve static files from S3
- Requires that https://github.com/ministryofjustice/cla_frontend/pull/719 be merged in first
- Had to add the AWS bucket hostname to the default,fonts, and styles CSPs as
- Fixed issue of node_modules and build happening at root due to WORKDIR not being set earlier
> LGA-1612 - Serve static files from S3

- helm_deploy/cla-frontend/values-production.yaml
- helm_deploy/cla-frontend/values-staging.yaml
- helm_deploy/cla-frontend/values-training.yaml
- helm_deploy/cla-frontend/values-uat.yaml
Moves GA settings from secrets to helm values
> LGA-1664 - Moving GA settings from secrets to helm values

- .circleci/config.yml
> LGA-1666 - circleci releases cleanup job

- cla_frontend/assets-src/javascripts/app/js/controllers/call_centre/assign_provider.js
- cla_frontend/assets-src/javascripts/app/partials/call_centre/case_detail.assign.html
- Update education script notes
- Add some logic so we show the default script notes for non education cases
> LGA-1726 - Update education script notes and add logic for default ones

- cla_frontend/assets-src/javascripts/app/partials/call_centre/case_detail.assign.html
Amends the script text according the card
> LGA 1738 Amend education assign script

- helm_deploy/cla-frontend/values-production.yaml
Remove whitelist from production
> LGA-1741 - Remove whitelist from production

- cla_frontend/settings/base.py
Added Maintenance mode setting
> LGA-1740 - Added Maintenance mode setting

- .circleci/define_build_environment_variables
- helm_deploy/cla-frontend/values-production.yaml
Reverts ministryofjustice/cla_frontend#752
> Revert "LGA-1742 - Update kubernetes production to use cases.civillegaladvice.service.gov.uk as the ingress host name"

- helm_deploy/cla-frontend/values-staging.yaml
Use staging backend on staging frontend
> Use staging backend on staging frontend

- .circleci/define_build_environment_variables
- helm_deploy/cla-frontend/values-production.yaml
Reverts ministryofjustice/cla_frontend#753
> Revert "Revert "LGA-1742 - Update kubernetes production to use cases.civillegaladvice.service.gov.uk as the ingress host name""

- cla_frontend/apps/call_centre/views.py
- cla_frontend/assets-src/javascripts/app/js/controllers/eligibility_check.js
- cla_frontend/assets-src/javascripts/app/partials/includes/eligibility.details.html
- cla_frontend/settings/base.py
- cla_frontend/templates/base.html
- helm_deploy/cla-frontend/templates/_helpers.tpl
- helm_deploy/cla-frontend/values.yaml
- Change the **finance script notes text** in the *details* column for family depending on whether
1. The case category is family
2. The `family_issue_feature_flag` is set to true
> LGA-1757 Finance script note changes for family

- package-lock.json
- package.json
Upgrades gulp-imagemin to a version that works (currently version 5, version 8 doesn't work).
> LGA 1619 - gulp build issues

- .circleci/config.yml
Removed deprecated setup-kube-auth and replaced it with needed code
Added the required contexts
> LGA 1913 remove setup-kube-auth

- .circleci/config.yml
Deploy staging to live cluster
Depends on https://github.com/ministryofjustice/cla_frontend/pull/768
> LGA-1921 deploy staging to live cluster

- .circleci/config.yml
Deploy training to new live cluster
> LGA-1923 deploy training to new live cluster

- cla_frontend/apps/call_centre/views.py
- cla_frontend/settings/base.py
- helm_deploy/cla-frontend/values.yaml
so far:
- added flag for switching new questions on and off
> LGA 1752 Add disregard questions 

- cla_frontend/assets-src/javascripts/app/js/controllers/eligibility_check.js
- cla_frontend/settings/base.py
- cla_frontend/templates/base.html
fix to get a flag to properly be used
> LGA 1752 disregards javascript fix

- cla_frontend/assets-src/javascripts/app/partials/includes/eligibility.details.html
Added html so question gets pulled through for disregards.
> LGA 1805 Guidance notes for disregards.

- .circleci/config.yml
- README.md
- npm_git_wrapper.sh
- requirements/base.txt
- requirements/testing.txt
switch git requirements to https
extra command in the circleci config for this switch to happen when npm install happens.
> LGA 1972 switch git requirements to https

- .circleci/authenticate_with_kubernetes_cluster
- .circleci/config.yml
K8S migration for Live Production.
Amends the deployment scripts in circle ci to deploy to live as well live1 now the namespace has been created.
> LGA 1805 - k8s migration production

- README.md
- cla_frontend/settings/.example.local.py
Updates readme about various environment variables and to ensure using Python 2.7 in virtual environment.
> Jo update readme

- .circleci/config.yml
removed reference to staging-live1 in circleci config.
> LGA 1954 Staging clean up

- .circleci/define_build_environment_variables
reads from a single host variable
> LGA 1957 Host variable cleanup

- helm_deploy/cla-frontend/templates/ingress.yaml
added ingress annotations to implement waf.
> LGA 2047 Implement web application firewall

- helm_deploy/cla-frontend/templates/ingress.yaml
removed firewall to stop timer being set.
> LGA 2047 removed firewall blocking JS

- helm_deploy/cla-frontend/templates/ingress.yaml
setting WAF to detection only as agreed with TAs.
> LGA 2047 Implementation of WAF monitoring

- .pre-commit-config.yaml
- helm_deploy/cla-frontend/templates/deployment.yaml
- requirements/lint.txt
The K8 probes are failing intermittently - removing whilst we investigate root cause
> Remove intermittently failing K8 probes

- docker/cla_frontend.ini
added alarm-backlog - to trigger a reset when the queue is full
added harakiri settings -  to stop workers taking too long.
> Further UWSGI changes for current live issue

- cla_frontend/assets-src/javascripts/app/js/controllers/case_list.js
- cla_frontend/assets-src/javascripts/app/partials/call_centre/case_list.html
- Removed hot key for case creation on case list screen.
- Have a boolean value which disables the button when a case is being created.
> LGA 2203: Prevent extra case creation

- helm_deploy/cla-frontend/templates/ingress.yaml
Step 1 Update the ingress file to contain both old and new ingresses.
This first change will need to be committed and once it is put through then a second commit should be merged that removes  the old ingress.
The weight of the original ingress should be set to zero before merging the first change.
> LGA-2124 Update the ingress file to v1.22

- cla_frontend/assets-src/javascripts/app/js/app.js
Anonymise Case reference when sending url to google analytics
> LGA-1903 - Anonymise Case reference when sending url to google analytics

- helm_deploy/cla-frontend/templates/ingress.yaml
Reverts ministryofjustice/cla_frontend#936
> Revert "Feature/lga 2309 enable modsecurity"

- helm_deploy/cla-frontend/templates/ingress.yaml
Reverts ministryofjustice/cla_frontend#941
> Revert "Feature/lga 2309 modsec"

- cla_frontend/assets-src/javascripts/app/js/controllers/call_centre/assign_provider.js
- cla_frontend/assets-src/javascripts/app/js/controllers/case_detail.js
- cla_frontend/assets-src/javascripts/app/js/controllers/diagnosis.js
- cla_frontend/assets-src/javascripts/app/js/controllers/eligibility_check.js
- cla_frontend/assets-src/javascripts/app/js/controllers/provider/accept_reject_case.js
- cla_frontend/settings/base.py
Cross-site GA tracking, this adds some of the main events into GA - more events to follow.
Public: https://github.com/ministryofjustice/cla_public/pull/1263
Frontend: https://github.com/ministryofjustice/cla_frontend/pull/956
Backend: https://github.com/ministryofjustice/cla_backend/pull/1178
Documentation: https://dsdmoj.atlassian.net/wiki/spaces/laagetaccess/pages/4952031380/End+to+end+CLA+Google+Analytics+reporting
> LGA-3156 (Spike LGA-3075) Add GTM for main common events

- cla_frontend/assets-src/javascripts/app/partials/call_centre/case_detail.assign.html
Changes the CHS specialist provider script to have minor alterations. 
THIS SHOULD NOT BE MERGED IN BEFORE KATHERINE'S IMPACT ASSESSMENT (Estimated 01/07/2024).
Discrimination, Housing and Debt:
Education:
https://dsdmoj.atlassian.net/browse/LGA-3159
> LGA-3159 Updates the CHS Script to include more information

- cla_frontend/templates/cla_provider/legal_help_form.jade
- Update debt collection partner to Advantis Credit Ltd from Marston Holdings
> LGA-3561: Update debt collection partner to Advantis Credit Ltd from Marston Holdings

- cla_frontend/assets-src/javascripts/app/js/controllers/case_detail.js
- cla_frontend/assets-src/javascripts/app/partials/call_centre/includes/case_notes.html
- cla_frontend/assets-src/javascripts/app/partials/provider/includes/case_notes.html
Formats list answers as a formatted list
> Correctly display list answers

- cla_frontend/assets-src/javascripts/app/partials/call_centre/includes/case_notes.html
- cla_frontend/assets-src/javascripts/app/partials/provider/includes/case_notes.html
- Fixes bad wording, to match the content record
> Fix bad case notes wording

- cla_frontend/assets-src/javascripts/app/js/controllers/personal_details.js
- cla_frontend/assets-src/javascripts/app/partials/includes/personal_details.html
Enable language selection when welsh is unchecked.
> LGA-3644 - Enable language selection when welsh is unchecked
