ministryofjustice/cla_frontend

- cla_frontend/assets-src/stylesheets/views/_legal-help-form.scss
- cla_frontend/templates/cla_provider/legal_help_form.jade
* bump up font size to help printed form legibility
* set box borders to black, again to aid clarity when form is printed
* typo: declaration is on page 5, not 4
* typo: "Partner's declaration", not "Partners declaration"
> Legal form printout css

- cla_frontend/assets-src/javascripts/app/js/controllers/call_centre/eod_details_modal.js
- cla_frontend/assets-src/javascripts/app/js/states/call_centre/case_detail.eod.js
- cla_frontend/assets-src/javascripts/app/partials/call_centre/case_detail.eod_details_modal.html
- cla_frontend/assets-src/javascripts/app/partials/call_centre/case_detail.html
• a single case (i.e. its one-to-one EOD) can have multiple open complaints
• operator managers can see a link from a case to complaints (with a count)
depends on [cla_backend#406](https://github.com/ministryofjustice/cla_backend/pull/406)
> complaints updates

- cla_frontend/settings/base.py
This change sets the expected env variable containing the application
version as APP_VERSION rather than APPVERSION to bring it into line
with convention.
> Standardise app version variable

- README.rst
- docker-compose-local.yml
- package.json
Updates include how to use docker compose to bring up cla_backend
(for local dev) and cla frontend.
I've also removed the need to have gulp and bower globally installed by
setting up npm script commands to use the local version of gulp and bower
installed in node_modules folder
> updates README

- package-lock.json
- package.json
By adding the 3 Karma browser extensions we should be able to add Unit testing to our TEST-cla job. 
I have made changes to the job and this PR should of had all the django and unit tests run together.
> Adds Karma browser extensions for testing

- cla_frontend/assets-src/javascripts/app/partials/includes/login.html
- cla_frontend/assets-src/javascripts/app/partials/includes/reset_password.html
- cla_frontend/assets-src/javascripts/app/partials/includes/session_expiring.html
Having an ng-submit attribute gives a javascript action that is triggered
on form submission, but if the action attribute is present then the
default action is not prevented.
> Remove action attribute from modal forms so that angular prevents default

- cla_frontend/assets-src/javascripts/app/partials/provider/case_detail.split.html
This addresses a bug discovered as a result of the angularjs version
being updated from 1.3 to 1.4. Providers reported to us that when they
tried to split a case the two matter type lists where not being populated
and were disabled.
At first it seemed as though the category drop down list was not triggering
the change event which in turn would populate the two matter type drop
down lists. The issue related to the scope that was being used, the
scope in the view and the scope watch being used in the controller were
different and thats why it was not working.
As part of this commit, I discovered that no tests were setup for this
feature or for any other features since mid-2015. The existing tests do
no work and I think this needs to be addresses as a bigger issue and
ticket. Therefore I …
> allow providers to split cases

- .bowerrc
- .dockerignore
- Dockerfile
I have re-ordered the Dockerfile. Here's why:
1. To learn about the project and how it's put together
2. To improve readability using more comments
3. To leverage Docker's build cache by grouping application dependencies together
Up to this point, the successful build times average around 7 to 8 minutes. [See the chart here](https://ci.service.dsd.io/view/CLA/job/BUILD-cla_frontend/buildTimeTrend).
There's still more work to do. The resulting docker image size is 1.42GB. There's 500MB of node modules! Such a large file takes times to push to an environment.
> Optimise dockerfile to leverage build cache

- tests/angular-js/e2e/caseList.js
There are some instances when there are other links on the page that
similar text to the filters for eg. "EOD" this appears in the filters
and in the case list for Operator managers. The issue with not scoping
the search is that if the elements were moved around the test would
be searching and clicking on the wrong link and could return a false
positive.
> Only search for filter links

- cla_frontend/apps/legalaid/postcode_lookup_views.py
- cla_frontend/apps/legalaid/tests/test_postcode_lookup_views.py
- cla_frontend/apps/status/tests/smoketests.py
- cla_frontend/settings/.example.local.py
- cla_frontend/settings/base.py
- cla_frontend/settings/testing.py
- requirements/base.txt
`postcodeinfo` is deprecated and EOL 2018-12-31. This replaces `postcodeinfo` with Ordnance Survey's Places API address lookup implemented in `cla_common`
Responses from view maintain compatiblity with frontend.
`cla_common` requirement temporarily switched to feature branch until PR is merged and tag exists so we can use `cla_common==0.3.0`
`requests` requirement version bumped to fix SSL issue
No longer propagates errors to frontend. Logs the error (to Sentry) and returns 404.
> LGA-394 Use cla_common postcode lookup

- .circleci/tag_and_push_docker_image
- cla_frontend/apps/status/urls.py
- cla_frontend/apps/status/views.py
- cla_frontend/settings/base.py
Replace ping response with a stub for compatibility with current deploys, as discussed, and future infra work.
Replace custom JsonResponse with native Django.
As a temporary workaround recommended by Cloud Platform, try [multiple docker pushes](https://github.com/ministryofjustice/cla_frontend/pull/629/commits/5e46123527372b0597c32e7b537e25a18a4fadfd) to workaround DSD registry timeouts.
This duplicates [PR 628](https://github.com/ministryofjustice/cla_frontend/pull/628), but shortens the branch name so DSD docker registry accepts the image.
Amended docstring to cover clarifying comment on PR 628.
> Stubbed PingJsonView to fix deploys

- .pre-commit-config.yaml
Ignore settings for flake8 until they're inverted in LGA-419, currently wallowing in the backlog and unlikely to make it into the next sprint.
None
> LGA-418 Pre-commit hooks

- .circleci/config.yml
- Dockerfile
In CircleCI, the test jobs are currently failing
https://www.python.org/dev/peps/pep-0517/ causes problems with cla_common and pip 19 uses it by default.
Using --no-use-pep517 does not work with pip install -r requirements.txt. The workaround is to downgrade to the previous version of pip.
We can upgrade to the next pip version if cla_common is made compatible with https://www.python.org/dev/peps/pep-0517/.
Same as ministryofjustice/cla_public#800
> LGA-477: Use pip version 18

- cla_frontend/assets-src/javascripts/app/partials/includes/personal_details.html
Displays the value of `contact_for_research_via` in the personal details area of the call handling system (alongside the value of the `contact_for_research` boolean field)
The issue was reported as the field not saving, but this was in fact the issue causing people to think that
> LGA-605 - Saved contact preference not displaying in CHS

- README.md
Providers use the training environment to test export and new features. Training should be as up to date as production and should be included in the deployment process.
> Add documentation for release to training environment

- cla_frontend/assets-src/javascripts/app/js/states/call_centre/case_detail.edit.diversity.js
- cla_frontend/assets-src/javascripts/app/partials/call_centre/case_detail.edit.html
Grey-out the Diversity tab, and redirect the `resolve` step if the check
is failed (like we already do on the Assign tab)
> LGA-851 - Make Diversity tab require eligible, in-scope case

- .circleci/config.yml
- .circleci/define_build_environment_variables
- .circleci/tag_and_push_docker_image
* Remove pushing images to abandoned Live-0 Cloud Platforms ECR repository
This project was pushing to old live-0 Cloud Platforms ECR repository which is no longer in use.
Cloud platforms have removed all non-production namespaces on live-0 ministryofjustice/cloud-platform-environments#1770
It seems the push to the ECR repository was added in anticipation of moving to kubernetes at the time.
However the Cloud platforms environments have changed since the original work.
When this project does move to cloud platforms managed environment, the relevant repository can be added.
Same as https://github.com/ministryofjustice/cla_backend/pull/606
> Remove pushing images to abandoned Live-0 Cloud Platforms ECR repository

- cla_frontend/assets-src/javascripts/app/partials/case_detail.outcome.html
Shows the full outcome name (eg "Callback 1") when hovering over the outcome code pill on the case details page. This is functionality the list page already has.
~~Requires https://github.com/ministryofjustice/cla_backend/pull/611 to function, but will not break catastrophically without it (the code will be marked up as an `abbr`, so a title will be expected, but the title will be empty)~~ The backend code it depends on has now been deployed
> LGA-915 - Add outcome description as abbr title on case page

- cla_frontend/assets-src/javascripts/app/partials/call_centre/case_list.html
- cla_frontend/assets-src/javascripts/app/partials/directives/callbackModal.html
Allow callback operators to view callback calendar so that they can pick a less busy time when scheduling callbacks
Previously there were no permissions around the callback calendar stopping operators accessing it. Instead the link to the callback calendar was not shown for non manager users. This PR displays the link to all call centre users (providers are not call centre users).
> LGA-890 - Allow callback operators to view callback calendar

- cla_frontend/assets-src/javascripts/app/js/controllers/case_detail.edit.js
- cla_frontend/assets-src/javascripts/app/js/controllers/diagnosis.js
- cla_frontend/assets-src/javascripts/app/js/services/models.js
- cla_frontend/assets-src/javascripts/app/partials/case_detail.edit.diagnosis.html
- cla_frontend/assets-src/javascripts/app/partials/case_detail.edit.eligibility.html
- cla_frontend/assets-src/stylesheets/views/_case.scss
- Front-end changes for https://github.com/ministryofjustice/cla_backend/pull/617
- Check if selected category one of letter of proceedings then eligibility_check.has_passported_proceedings_letter to True
- Skip financial checks when eligibility_check.has_passported_proceedings_letter is True
- Add unique class to summary blocks and to heading wrappers so that they can be styled differently 
> LGA-889 - Public law: passport clients with letter of proceedings

- bower.json
- cla_frontend/assets-src/javascripts/app/js/app.js
- cla_frontend/assets-src/javascripts/app/js/controllers/search.js
- tasks/gulp/_paths.js
One of the features of the CHS system is in searching for details for a specific client. When searching for client details, CHS users can use search terms such as (a client's) name, postcode in order to find the intended person. After searching for a client, the search terms used are shown in the browser, exposing the client's personal details 
Before: After searching for a client on the CHS system using key terms like their name or address, the information used in searching for the client (e.g. name, postcode etc) will appear in the URL and be exposed.
Now: After searching for a client, if the page contains a query string key containing search, that page will not get sent to GA.
> LGA-1124 Anonymise all search data being sent to CHS Google Analytics

- Dockerfile
- requirements/base.txt
This version of cla_common updates the operator hours constant
Also fixes a build fail that emerged recently, by upgrading pip on its own before using it to upgrade anything else
> LGA-1053 - Require updated cla_common library

- cla_frontend/assets-src/javascripts/app/js/app.js
- Removes user data that gets sent to Google Analytics upon refreshing the page
- Only takes place when eg. a CHS member searches for a user, then refreshes the page. 
- This is because when a CHS member searches for a user, the 'search' word appears in the URL
I've changed whatever the search term query is to 'redacted' as done here in a previous piece of work https://github.com/ministryofjustice/cla_public/commit/d965f7dd9447219b895296cf03c2bdfea2e46808. 
E.g. if a CHS members searches for a person called 'Bob', it would show as `localhost:8001/call_centre/search=redacted`
> LGA-1211 Ensure refreshing CHS search pages does not send data to GA

- cla_frontend/apps/core/middleware.py
- cla_frontend/apps/core/testing/test_views.py
- cla_frontend/apps/core/urls.py
- cla_frontend/apps/core/views.py
- cla_frontend/settings/base.py
- cla_frontend/templates/base.html
- cla_frontend/templates/maintenance.html
- cla_frontend/urls.py
Add maintenance page
Insert new blocks into base template to allow extending templates to customise content
The maintenance page returns a 503 status code. This will allow angular request to display an error message if the site is put in maintenance mode whilst still on page
/status/ping.json is exempt from being redirected when in maintenance mode, if not then the loadbalancer healthchecks will fail and the instance will be taken out of routing
>  LGA-1348 - Adding maintenance page

- cla_frontend/assets-src/javascripts/app/js/directives/callbackModal.js
- requirements/lint.txt
Reduces it to 30 minutes ie causing it to show the first window starting
more than half an hour away. This currently can't be reduced to zero (to
show the next window from now) or made negative (to show the current
window) as the backend will not allow scheduling callbacks at those
times
Closes #692, the same PR with a different branch name
> LGA-1416 - Reduce call back scheduling delay

- requirements/base.txt
cla_common has been updated with [new operator hours](https://github.com/ministryofjustice/cla_common/pull/98)
This PR updates cla_frontend to use that version of the library, and thus the new hours. It should not be merged until we're ready to deploy this behavioural change.
> LGA-1423 - Update cla_common for restored operator hours

- cla_frontend/assets-src/javascripts/app/js/app.js
- cla_frontend/assets-src/javascripts/app/js/controllers/diagnosis.js
- cla_frontend/assets-src/javascripts/app/js/states/case_detail.edit.eligibility.js
- cla_frontend/assets-src/javascripts/app/partials/case_detail.edit.diagnosis.html
- cla_frontend/assets-src/javascripts/app/partials/case_detail.edit.eligibility.html
- cla_frontend/assets-src/stylesheets/views/_case.scss
- **Finances part of the form:** Scrolls down to just above whatever inner tab has been selected under the `Finances` tab
- **Scope part of the form:** Scrolls down and ensures the questionnaire is in full view every time you click the 'next' button under the `Scope` tab
Comments have been added to understand why mutation observer is used and how it works for the scope functionality in the `cla_frontend/assets-src/javascripts/app/js/states/case_detail.edit.eligibility.js` file
When I checked the dimensions (height) of the form in the code and after in the browser when reaching the last stage (ie. the `Delete scope diagnosis` button is present, it would be different. Believe this is due to some JS/angular scripts running, but I do not know entirely why.
**How it looks like:**
(_Every time …
> LGA-365 Scrolling Down

- cla_frontend/assets-src/javascripts/app/js/controllers/call_centre/assign_provider.js
- cla_frontend/assets-src/javascripts/app/partials/call_centre/case_detail.assign.html
Disable the Assign provider button during form submission
Button should also remain disabled after a successful form submission, so that the user does not click it again during the redirect to the case listings.
> LGA-1501 - Disable the Assign provider button during form submission 

- Dockerfile
Downgrade/pin to pip to pip18.1 because pip21 dropped support for python2.7
> Downgrade pip to 18.1

- Dockerfile
- bower.json
- cla_frontend/apps/core/context_processors.py
- cla_frontend/apps/status/views.py
- cla_frontend/settings/base.py
- cla_frontend/templates/base.html
- cla_frontend/wsgi.py
- package-lock.json
- package.json
- requirements/base.txt
Switches from Raven library to Sentry SDK, and starts passing an environment tag.
- SENTRY_DSN value, which has now been added using cla_frontend-deploy
- Removed raven front-end(javascript) integration as the upgrade work for that needs to be done as part of https://dsdmoj.atlassian.net/browse/LGA-1494
- Pin pip to version 18.1 as the latest pip21 dropped support for python2.7
> LGA-1506 - Replace raven Python library with Sentry SDK

- .circleci/config.yml
- .circleci/tag_and_push_docker_image
Push to dockerhub instead of dsd docker registry
Remove specifying docker hub repoistory when doing docker login
The `$DOCKER_HUB_REGISTRY` had to be removed from the `docker login` otherwise the push was failing with: `dockerhub denied: requested access to the resource is denied`
> LGA-1630 Push to dockerhub instead of dsd docker registry

- bower.json
- cla_frontend/apps/core/context_processors.py
- cla_frontend/assets-src/javascripts/app/js/app.js
- cla_frontend/assets-src/javascripts/app/js/services/network.js
- cla_frontend/assets-src/javascripts/vendor/raven.config.js
- cla_frontend/settings/base.py
- cla_frontend/templates/base.html
- tasks/gulp/_paths.js
- tests/angular-js/karma.conf.js
- tests/angular-js/unit/AlternativeHelpServiceSpec.js
- Add sentry integration with the Angular frontend
- Renamed SENTRY_DSN environment variable to SENTRY_PUBLIC_DSN
- Requires https://github.com/ministryofjustice/cla_frontend-deploy/pull/124
I decided to introduce a new sentry environment variable instead of reusing the existing one because I felt that it needed to be explicit that this value will be public(even though we were using a public value before), so if someone changed SENTRY_DSN to a private value then it wouldn't be shared on the frontend.
After conversation with @exonian we decided to just have the SENTRY_PUBLIC_DSN and remove the existing SENTRY_DSN. At a later point, if someone wishes to use a private DSN value, they should introduce SENTRY_PRIVATE_DSN environment variable. See …
> LGA-1494 - Sentry integration with the Angular frontend

- cla_frontend/assets-src/javascripts/app/js/app.js
Check if Sentry is setup before require angular dependency
Currently on local development were sentry is not setup, angular throws an exception that `ngRaven` module is not defined which breaks the frontend app(no further javascript is executed)
This PR checks if Raven/Sentry has been setup before requiring the `ngRaven` angular module
> Check if Sentry is setup before require angular dependency

- helm_deploy/cla-frontend/templates/_helpers.tpl
- helm_deploy/cla-frontend/values-staging.yaml
- helm_deploy/cla-frontend/values.yaml
Ports any required variables from cla_frontend-deploy's pillar secrets to our Helm chart
Most are instructed to use secrets, and have been added in `values.yaml`
Those which need `Values.host` are in the helpers file
Those which are not secret, but differ by env, are in `values-staging.yaml`, and an equivalent change will be required in each other env
The secrets have been uploaded to k8s separately, outside of code
> LGA-1663 - Add env vars from secrets

- .circleci/config.yml
- .circleci/define_build_environment_variables
- .circleci/tag_and_push_docker_image
- cla_frontend/apps/status/smoketests/basic.py
- cla_frontend/settings/base.py
- helm_deploy/cla-frontend/templates/_helpers.tpl
- helm_deploy/cla-frontend/templates/ingress.yaml
- helm_deploy/cla-frontend/values-staging.yaml
- helm_deploy/cla-frontend/values.yaml
- template_deploy/define_build_environment_variables
- template_deploy/tag_and_push_docker_image
Deploy to cloud platforms live-1 kubernetes cluster through circleci
- Refactored the smoketests so that the application does not make an external request during the smoketests as the pod is not ready at the early point when the smoketests are running.
- Renamed previous build job to `build_for_template_deploy` and repurposed the build job to build our new Dockerfile.
- Move the old `.circleci/define_build_environment_variables` and `.circleci/tag_and_push_docker_image` scripts to the `/template_deploy` directory and removed the non template-deploy logic from them.
- Created new `.circleci/define_build_environment_variables` and `.circleci/tag_and_push_docker_image` script with just the logic for pushing and tagging images for cloud platforms kubernetes
> LGA-1614 - circleci staging deploy

- cla_frontend/apps/status/smoketests/basic.py
Fixes the /ready/ probe that checks that our js file is being served
This was still looking for it to be being served by the pod at /static/, which is not the case with s3
> LGA-1612- Get js path for probe from staticfiles

- cla_frontend/settings/base.py
- cla_frontend/settings/docker.py
- Sends django.request and root loggers to the stdout
- Moved "mail_admin" logging handler to settings/docker.py as template deploy still needs that logger handler (we no longer need it because we are sending our logs to the stdout)
- Moved the `require_debug_false` and `require_debug_true` logging filters to settings/docker.py as some template deploy logging handlers still need those filters.
> LGA-1642 logging to kibana

- .circleci/config.yml
Removes the ECR login step from the build_for_template_deploy job
It got broken by some changes to env var names. We could probably recreate the env vars it needs, but it shouldn't be in that job anyway (template deploy only uses dockerhub, and the k8s deploys use different build jobs)
Cherry-picked from a feature branch so that other branches can use it now
> Remove ECR login from legacy build step

- requirements/base.txt
Update cla_common to latest version to pull in address lookup changes
Requires https://github.com/ministryofjustice/cla_frontend-deploy/pull/127 for testing
> LGA-1629 - Update cla_common to latest version to pull in address lookup changes

- helm_deploy/cla-frontend/values-production.yaml
- helm_deploy/cla-frontend/values-uat.yaml
- helm_deploy/cla-frontend/values.yaml
Update staging and training ingresses to use custom domain
Before merging this PR in the following environment variables must to be created in the laa-cla-frontend circleci context:
- STAGING_HOST=staging.cases.civillegaladvice.service.gov.uk
- TRAINING_HOST=training.cases.civillegaladvice.service.gov.uk
> LGA-1671 Update staging and training ingresses to use custom domain

- bin/production_deploy.sh
- bin/staging_deploy.sh
- bin/training_deploy.sh
- helm_deploy/cla-frontend/templates/ingress.yaml
- helm_deploy/cla-frontend/values-production.yaml
- helm_deploy/cla-frontend/values-training.yaml
- helm_deploy/cla-frontend/values-uat.yaml
- Remove whitelists for training and production environments
- Remove setting of tls certificate in deployment files as it is set in values.yaml
Wrapping the ingress annotation`nginx.ingress.kubernetes.io/whitelist-source-range` in an if condition that checks the if whitelist is not empty is required because a `nginx.ingress.kubernetes.io/whitelist-source-range` annotation with an empty value will result ingress failing and returning a 503 for all requests.
> LGA-1729 - Remove whitelists for training and production environments

- bin/training_deploy.sh
- helm_deploy/cla-frontend/templates/_helpers.tpl
Add pingdom ips to whitelist
Remove `pingdomIPs` environment variable from training deployment as it is not behind a whitelist
> LGA-1667 - Add pingdom ips to whitelist

- .circleci/define_build_environment_variables
Read current production host name from $CLOUD_PLATFORM_PRODUCTION_HOST environment variable
Current kubernetes production host name is laa-cla-frontend-production.cloud-platform.service.justice.gov.uk this PR updates the host environment variable to reflect that.
A separate PR will be raised to changed the environment variable to $PRODUCTION_HOST as part of the final switch over
> LGA-1742 - Read current production host name from $CLOUD_PLATFORM_PRODUCTION_HOST environment variable

- .circleci/define_build_environment_variables
- helm_deploy/cla-frontend/values-production.yaml
- Update kubernetes production to use cases.civillegaladvice.service.gov.uk as the ingress host name
- Use the secretName defined in the deploy files
When this PR is merged the production ingress will use the hostname cases.civillegaladvice.service.gov.uk
> LGA-1742 - Update kubernetes production to use cases.civillegaladvice.service.gov.uk as the ingress host name

- cla_frontend/settings/base.py
Use CLA_PROVIDER_SECRET_ID for provider secret if it is set otherwise use CALL_PROVIDER_SECRET_ID env var
> LGA-1750 - Use CLA_PROVIDER_SECRET_ID for provider secret

- helm_deploy/cla-frontend/values-staging.yaml
Use custom domain for staging backend instead of cloud platforms domain
> Use custom domain for staging backend instead of cloud platforms domain

- cla_frontend/assets-src/javascripts/app/js/services/models.js
- cla_frontend/assets-src/javascripts/app/js/states/call_centre/case_detail.edit.assign.js
- cla_frontend/assets-src/javascripts/app/partials/call_centre/case_detail.edit.html
- Add functionality to check if category is non cla (AKA family)
- Disables the `assign` tab if the category is family and prevents it from being accessed. Also writes a message on the banner near the of the screen (**pictured below**)
- Rebased off the [other ticket](https://github.com/ministryofjustice/cla_frontend/pull/758). The commits for this branch start from `f1bd484`
**Error message**
Will give Rosie and Sannah a demo to find out what they think of the error message and get possible suggestions on what it could be.
_Picture of message written after clicking on the `assign` tab and the category is family_
**Extra commits**
Rebased off the [other ticket](https://github.com/ministryofjustice/cla_frontend/pull/758) as it contained the `family_feature_flag` code. …
> LGA-1754 CHS family routing

- bower.json
- cla_frontend/assets-src/javascripts/vendor/analytics.js
- package-lock.json
- package.json
- tasks/gulp/_paths.js
- tests/angular-js/karma.conf.js
- Moves packages that have same the version from bower to npm
- Change references to these packages where ever they are used 
- Remove unused package and random package reference (explained below)
> Follow up from [LGA-79 ](https://dsdmoj.atlassian.net/browse/LGA-79?focusedCommentId=175481) which includes a table in the comment section that shows which packages in bower have the same version in npm
During the package moving process I removed:
- `extend` from npm seeing as it is not used anywhere
- the path reference for a package `vendor/ui-router-extras/release/ct-ui-router-extras.js` from `_paths.js` as it does not seem to be installed anywhere
**Stop GA from sending unnecessary requests**
From my last commit can confirm the issue pictured below seems to be fixed by just clearing …
> LGA-1619 Move packages from bower to npm

- .circleci/config.yml
- bin/production_deploy.sh
- bin/staging_deploy.sh
- bin/training_deploy.sh
- bin/uat_deploy.sh
- helm_deploy/cla-frontend/templates/ingress.yaml
- helm_deploy/cla-frontend/values.yaml
- Add variable placeholders for cluster `name` and `weight` in `values.yaml`
- Add annotations to `ingress.yml` referencing the variables above
- Add parameters to all deployment scripts for setting (overriding) the cluster `name` and `weight` in `values.yaml`
- Create a `ingress-cluster` configmap with following values
- `name` The cluster name i.e `blue` or `green`
- `weight` The weighting of traffic that cluster should receive
- Update the circle config to read contents of `ingress-cluster` configmap and pass it to the deploy scripts as environment variables.
Similar to https://github.com/ministryofjustice/cla_backend/pull/736
Command used to create configmap: `kubectl create configmap ingress-cluster --from-literal=name=blue --from-literal=weight=100`
> LGA-1894 - Add external DNS annotations to ingress

- .circleci/config.yml
- Create deploy steps for uat namespace in live cluster
Have moved over secrets and configmap variables manually and created env vars in circleci context as `laa-cla-frontend-live-uat`
> LGA-1922 Create deploy steps for uat namespace in live cluster

- .circleci/authenticate_with_kubernetes_cluster
- .circleci/config.yml
Create reusable script to authenticate with cluster.
Remove missed setup-kube-auth in cleanup_merged job
Add `cleanup_merged` for each cluster
> LGA-1937 - Create reusable script to authenticate with cluster

- cla_frontend/settings/base.py
Fix mismatching inline-script hash on production
We do not allow arbitrary inline-scripts to execute. Instead we take a hash of the inline script and only allow scripts matching that hash to execute.
Production is raising the following error in the console:
```
Either the 'unsafe-inline' keyword, a hash ('sha256-I2LOM6esOcAN2kEMLd3BbCCa/vshtQ3D4lkR5YJYKss='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.
```
See https://github.com/ministryofjustice/cla_frontend/pull/778 for a long term fix
> Fix mismatching inline-script hash on production

- cla_frontend/apps/call_centre/views.py
- cla_frontend/assets-src/javascripts/app/js/app.js
- cla_frontend/assets-src/javascripts/app/js/controllers/eligibility_check.js
- cla_frontend/assets-src/javascripts/app/js/services/cla_features.js
- cla_frontend/assets-src/javascripts/app/js/services/models.js
- cla_frontend/assets-src/javascripts/app/partials/includes/eligibility.details.html
- cla_frontend/settings/base.py
- cla_frontend/templates/base.html
Add angular service to detect enabled feature flags
Also switched from using an inline script with global variables to using html attribute for enabled feature names
The issue with using the inline script was that the hash had to be regenerated whenever there was a change to
the feature flag state and would have resulted to having hashes of multiple feature flag states
> LGA-1964 - Add angular service to detect enabled feature flags

- cla_frontend/assets-src/javascripts/app/partials/includes/eligibility.details.html
- cla_frontend/assets-src/javascripts/app/partials/includes/eligibility.finances.html
Moves disregards questions from the Detail's sub-tab to the Finances sub-tab in CHS.
Ticket  LGA-1752 was created to add the disregards questions on the CHS. This work was completed and demoed to HGS. They pointed out that having it positioned in ‘Details’ sub-tab in the finances section could be confusing for operators as they may not need to ask the questions at the point which could lead to increased call times. It was determined that it would be better if the questions appeared under the ‘Finances’ sub-tab of the Finances tab
For this change to be visible the environment variable SHOW_DISREGARDS_FEATURE_FLAG needs to be set to TRUE
> LGA -1973 move disregards

- .circleci/config.yml
Removed deployments linked with CLA Frontend UAT Live-1
'build_for_template_deploy' deployment mentioned in the ticket was removed in previous commit.
> LGA 1953 CLA Frontend UAT Live-1 Clean-up

- .circleci/config.yml
Removed deploy reference to training_deploy_live_1 in circleci config
> LGA-1955-CLA-Frontend-Training-Live-1-Clean-up

- cla_frontend/apps/status/smoketests/__init__.py
- cla_frontend/apps/status/smoketests/basic.py
- cla_frontend/settings/base.py
- helm_deploy/cla-frontend/templates/deployment.yaml
- helm_deploy/cla-frontend/templates/socket-server-deployment.yaml
Restore pod probes
Remove smoke tests that contain request to the current app from the ready tests. 
Send INFO level logs to the console so that send info level logs to our logging system
Remove smoke tests that contain request to the current app from the ready tests as the app might not be ready to deal with these requests yet. In theory this shouldn't be an issue because `initialDelaySeconds` is set. However the ready probes fail when these smoke tests are executed as part of the ready probes.
https://dsdmoj.atlassian.net/browse/LGA-2070
> LGA-2070 - Restore pod probes

- Dockerfile
- docker/cla_frontend.ini
- helm_deploy/cla-frontend/templates/deployment.yaml
Amended UWSGI setup to increase http-workers to 5.
Added settings in UWSGI and created a new liveness probe that checks if a file is there or not.
- Docker creates the file
- WSGI alarm setting removes the file when it triggers
- Liveness probe checks for the file, pod gets reset when that file is not found.
> Amend UWSGI set up and Add Liveness Probe

- docker/cla_frontend.ini
Enable Vacuum setting for uwsgi
Increase number of workers to 4
Decrease number of http-workers to 2 - Still trying to figure the impact of this config setting
Increase harakiri to 30 seconds to stop legitimate requests being killed off early
The vacuum option will instruct uWSGI to clean up any temporary files or UNIX sockets it created, such as HTTP sockets, pidfiles, or admin FIFOs
> Enable Vacuum setting for uwsgi

- docker/cla_frontend.ini
Amended harakiri from 30 to 60 to be less aggressive with timings.
Used this article as well as others to increase the timing, there are potential other changes we could bring in as well but would require further investigation.
https://www.bloomberg.com/company/stories/configuring-uwsgi-production-deployment/
> LGA 2105 - CHS users reporting intermittent slowness 

- helm_deploy/cla-frontend/templates/ingress.yaml
Disable modsecurity json parser
This slows down requests with large json bodies like /provider/csvupload/
List of mod-security conf rule ids can be found at https://github.com/SpiderLabs/ModSecurity/blob/v3/master/modsecurity.conf-recommended#L29-L30
> Disable modsecurity json parser

- .circleci/config.yml
circleci image upgrade
note: now use an orb for install node version, and then just use the most recent node cimg.
> LGA 1880 upgrade circleci

- helm_deploy/cla-frontend/values-production.yaml
- helm_deploy/cla-frontend/values-staging.yaml
- helm_deploy/cla-frontend/values-training.yaml
- helm_deploy/cla-frontend/values-uat.yaml
Communicate with backend using a service name
**Requires** https://github.com/ministryofjustice/cla_backend/pull/851
This an attempt to alleviate the issue of frontend sometimes timing out/reported sluggishness when trying to reach backend.
This fix will keep frontend to backend communication within the cluster instead request leaving the cluster and coming back again.
Requires the following PRs to allow namespaces to communicate with each other using a service name:
- production - https://github.com/ministryofjustice/cloud-platform-environments/pull/8704
- training - https://github.com/ministryofjustice/cloud-platform-environments/pull/8702
- staging - https://github.com/ministryofjustice/cloud-platform-environments/pull/8701
> LGA-2251 - Communicate with backend using a service name

- .circleci/config.yml
- requirements/base.txt
> LGA-1965 - Add end-2-end tests to CircleCI

- .circleci/config.yml
Explicitly use laa-cla-frontend-app-ecr context when access to ecr is required
We had ECR credentials in both laa-cla-frontend and laa-cla-frontend-app-ecr contexts. I have removed it from the laa-cla-frontend context and made sure that the laa-cla-frontend-app-ecr context is used anywhere ECR access is required
> LGA-2369 - Explicitly use laa-cla-frontend-app-ecr context when access to ecr is required

- cla_frontend/assets-src/javascripts/app/partials/case_detail.edit.diagnosis.html
Do not submit the entire scope diagnosis form when creating a scope
This was causing the form submission and the on-click handler for that button to be triggered simultaneously.
> LGA-2392 - Do not submit the entire scope diagnosis form when creating a scope

- .circleci/config.yml
Update build job docker image to use latest cloud-platform image.
The previous cloud-platform/tools:circleci image is out of date and is using out of date ubuntu version that is missing latest lets encrypt root certificate which was causing our slack notifications not to go out.
> LGa-2412  - Update build job docker image to use latest cloud-platform image

- .bowerrc
Changes the bower registry in bowerrc to the herokuapp link.
> LGA-2617 Updated registry to herokuapp

- cla_frontend/assets-src/javascripts/app/js/controllers/eligibility_check.js
- cla_frontend/assets-src/javascripts/app/js/services/incomeWarningsService.js
- cla_frontend/assets-src/javascripts/app/partials/includes/eligibility.details.html
Skip financial assessment for under eighteens
There is a problem in the pipelines where bower fails. As this happens before we build, I have added workaround `"strict-ssl": false,` **This should NOT be merged in**. This is being used to enable end to end testing by getting the build info. 
We need to create a ticket and decide how to handle the bower errors as this will block us from merging in the future. 
Some resources:
- [Stackoverflow](https://stackoverflow.com/questions/76089161/how-to-refresh-bower-package-certificate) - Question asked same time as our pipelines began failing
- [Github Issue](https://github.com/bower/registry/issues/304)
- [Old Github Issue with newer replies since this incident](https://github.com/bower/bower/issues/2608)
> LGA-2590 - Skip financial assessment for under eighteens

- .circleci/config.yml
Removes the context laa-cla-frontend-app-ecr from the config circle ci file. This context is now no longer needed but is used in the current config build of cla_frontend. By removing it from the config file, we can delete the obsolete context from circle ci.
> Removed context for frontend app ecr

- cla_frontend/settings/.example.local.py
Adds comments in the example.local.py file, documenting a unique interaction where changing an environment variable will not have the desired effect unless the Zone Profile dictionary is also updated.
> LGA-2677: Updated documentation regarding BACKEND_BASE_URI in .example.local.py

- cla_socketserver/app.js
Fix adminApp.install to receive a SocketNamespace function which it is expecting to receive instead of the  SocketServer object which it is currently receiving
This was causing the CHS not to receive notifications in realtime
> LGA-2673  fix admin app socket namespace

- helm_deploy/cla-frontend/values.yaml
This PR gives access via Global Protect VPN, since Digital VPN is disappearing. See more here: https://github.com/ministryofjustice/cla_backend/pull/1109
Tested successfully on the branch environment, with just GlobalProtect VPN enabled: https://allow-access-from-globalprot-laa-cla-frontend-uat.apps.live-1.cloud-platform.service.justice.gov.uk/auth/login/
This covers the "Global Protect users can access CLA Frontend" part of [LGA-2885](https://dsdmoj.atlassian.net/browse/LGA-2885).
This PR doesn't remove access from "MoJ Digital Wifi & Digital VPN". Rather than switch off access from that in this same deployment, I suggest we have a short period of overlap, where both VPNs can be used, to allow all devs to check the new arrangement works for everyone. So removing that IP from the list can …
> LGA-2885 Allow access from Global Protect VPN

- cla_frontend/assets-src/javascripts/app/js/controllers/call_centre/assign_provider.js
- cla_frontend/assets-src/javascripts/app/partials/call_centre/case_detail.assign.html
Enables the manual allocation of all education cases regardless of if a provider is suggested or not.
This assigns the case a outcome code of `MANALC` meaning it will impact the best fit provider allocations.
> LGA-2988: Enabled manual allocation of all education cases

- helm_deploy/cla-frontend/templates/ingress.yaml
Hide All environments from search engines.
Previously the annotation `nginx.ingress.kubernetes.io/server-snippets` was used on the ingress, however there is no such annotation, the correct annotation is `nginx.ingress.kubernetes.io/server-snippet`
> LGA-2989 - Hide All environments from search engines

- cla_frontend/assets-src/javascripts/app/js/controllers/eligibility_check.js
Default skipped means eligibility to false and reset to false after each time it's tracked.
> LGA-3156 reset skipped value for each means test in CHS

- bin/staging_deploy.sh
- Adds the Shared LAA IP Ranges to the staging_deploy.sh, this was erroneously missed in this Pull Request:
#975 
> LGA-3272: Adds the Shared LAA IP Ranges to the staging environment
